name: percent_indicator_example
description: A new Flutter project.

version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.11.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  percent_indicator:
    path: ../

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
